Header Alignment & Removed old files
PoojaMittal2842/Delhi-Tourism pull request #149
Opened 2021-03-23 17:53 UTC by KIIRTHANA

2021-03-23 18:02 UTC, maverick1910 requested changes
Please attach a picture of your work for merge

2021-03-24 12:56 UTC, maverick1910 approved these changes
merged and accepted !!

2021-03-24 12:56 UTC, merged

2021-03-25 19:26 UTC, KIIRTHANA commented
Thank you!!

2021-04-14 17:00 UTC, maverick1910 reviewed
Label Changed